# Generated by Django 4.2.5 on 2023-09-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodBongo', models.TextField(default='')),
                ('category', models.CharField(choices=[('GR', 'Groceries'), ('MW', 'Mens&Women'), ('SH', 'Shoes'), ('DY', 'Dairy'), ('HD', 'Home-Decor'), ('CS', 'Cosmetics')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
