# Generated by Django 4.2.5 on 2023-09-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bong', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prodBongo',
            new_name='prodapp',
        ),
    ]
