# Generated by Django 4.2.5 on 2023-09-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bong', '0002_rename_discount_price_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodapp',
            new_name='prodBong',
        ),
    ]
