# Generated by Django 4.2.5 on 2023-10-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bong', '0003_rename_prodapp_product_prodbong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GR', 'Groceries'), ('MW', 'Mens&Women'), ('DY', 'Dairy'), ('SH', 'Shoes'), ('HD', 'Home-Decor'), ('CS', 'Cosmetics')], max_length=2),
        ),
    ]
